---
# Cloudera playbook

- name: Configure Cloudera Manager Repository
  hosts: cdh_servers
  roles:
    - cm_repo
  tags: cm_repo

- name: Install rngd
  hosts: cdh_servers
  roles:
    - role: rngd
      when: cdh_install_rngd
  tags: rngd

- name: Install Java
  hosts: cdh_servers
  roles:
    - role: java
      when: cdh_install_java 
  tags: java

- name: Install MariaDB and create databases
  hosts: db_server
  roles:
    - role: mariadb
      when: cdh_install_mysql 
  tags: mysql

- name: Install MySQL Connector
  hosts: utility_servers:master_servers
  roles:
    - role: mysql_connector
      when: cdh_install_mysql 
  tags: mysql

- name: Install MIT KDC Server
  hosts: krb5_server
  roles:
    - role: krb5_server
      when: krb5_kdc_type == 'mit'
  tags: krb5

- name: Configure EPEL Repository
  hosts: scm_server
  roles:
    - epel
  tags: epel

- name: Install Cloudera Manager Agents
  hosts: cdh_servers
  roles:
    - cm_agents
  tags: cm_agents

- name: Install Cloudera Manager Server
  hosts: scm_server
  roles:
    - scm
  tags: cm_server,cluster_template

- name: Install CDH
  hosts: scm_server
  roles:
    - role: cdh
      when: cdh_install_cluster
  tags: cluster_template

